### ISSUE TITLE
Please try to make yours E-mail client more accessible with Orca screen reader

### ISSUE THREAD

**Issue by JanuszChmiel** [eworm-de/claws-mail#1]
When I have ried yours E-mail client for The first time, I have been overjoied. I have thought, that it will be fully accessible including E-mail folder names and especially folder E-mail content. Unfortunnately, it is not true. I AM even very sad because yours app do not use shared memory so it is even possible to use it on Android device, when Termux, Proot and some Linux distro will run it by using X11 and VNC protocol support.
Do you think, that it would be too complex or even impossible to recoe GUi of yours app so also E-mail folder names and messages list can be made accessible with Orca screen reader? Or is it allready done, but I must setup something?
Thank you very much for yours answers.

**Comment by eworm-de** [comment]
Orca is a screen reader providing accessibility for blind people, no?

I am just an occasional contributor to the mail client claws-mail. This repository is just a mirror or fork of the [upstream repository](https://git.claws-mail.org/?p=claws.git;a=summary).
You should send your request to upstream developers via [bug tracker](https://www.thewildbeast.co.uk/claws-mail/bugzilla/index.cgi) or [mailing list](https://www.claws-mail.org/MLs.php).
