### ISSUE TITLE
Hostname visible in the page source code

### ISSUE THREAD

**Issue by kosmosgit** [eworm-de/claws-mail#2]
I have the following problem. If someone else composes and sends a message with their mail account on my computer, the host name of the computer is always transmitted as well. The recipient sees the source text of the received mail. The name of the host computer, which has nothing to do with the actual sender and should not be visible.

Could prevent the sending of the host name in general or make it selectable.

This could also be a problem in terms of data protection law, since the owner of the computer does not want to be associated with the sender of an e-mail.

**Comment by eworm-de** [comment]
This is just a copy of the upstream repository. Please send your concerns to upstream project.
